name: batt_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  material_dialogs: ^1.1.5
  country_code_picker_plus: ^0.0.9
  get: ^4.6.6
  otp_text_field: ^1.1.3
  omni_datetime_picker: ^2.0.5
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  http: ^1.2.2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.3
  intl: ^0.19.0
  dropdown_search: ^6.0.1
  drop_down_list: ^0.0.8
  firebase_messaging: ^15.2.2
  mailer: ^6.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  sms_autofill: ^2.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  

  assets:
    - assets/images/
    - assets/icons/home_icons/
    - assets/icons/bar_icons/
    - assets/icons/profile_icons/
    - assets/gif/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

